site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md
    - 'Project': README.md
    - 'Datasets': README.md
    - 'Software': README.md
    - 'Vocabularies': README.md
    - 'People': README.md
    - 'Collaborations': README.md

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io

theme: readthedocs
