site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md
    - Projects : projects/projects.md
    - Datasets: datasets/datasets.md
    - Software: software/software.md
    - Vocabularies: vocabularies/vocabularies.md
    - People: people/people.md

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io


theme:
  name: material
