site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md
    - Project : project.md
    - Datasets: datasets.md
    - Software: software.md
    - Vocabularies: vocabularies.md
    - People: people.md

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io


theme: readthedocs    