site_name: Semantic Technologies team at ZB MED
nav:
    - Home: index.md
    - 'Project': index.md
    - 'Datasets': index.md
    - 'Software': index.md
    - 'Vocabularies': index.md
    - 'People': index.md
    - 'Collaborations': index.md

# Repository
repo_name: zbmed-semtec/zbmed-semtec.github.io
repo_url: https://github.com/zbmed-semtec/zbmed-semtec.github.io

theme: readthedocs
